### ISSUE TITLE
Please remove our API key

### ISSUE THREAD

**Issue by Manishearth** [jkeesh/vaccinateil#1]
Hi!

You have VaccinateCA's API key hardcoded in your map code. It's set to only work from our website, however we do get alerted whenever the key is found in a public source repo. Could you please remove it?

**Comment by jkeesh** [comment]
my mistake, was trying to modify and missed that, will remove

**Comment by jkeesh** [comment]
If you are referring to the key in map.html, that is removed

**Comment by Manishearth** [comment]
Thanks!
